
E1 = [{"x": 0, "y": 0, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 0.5, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 0, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 0.5, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 0, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 0.5, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 0, "y": 1, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 1.5, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 1, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 1.5, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 1, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 1.5, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 0, "y": 2, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 2.5, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 2, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 2.5, "terrain": "desert", "cougar": False, "bear": True, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 2, "terrain": "desert", "cougar": False, "bear": True, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 2.5, "terrain": "forest", "cougar": False, "bear": True, "structure": {"present": False, "colour": None, "type": None}}]

E2 = [{"x": 0, "y": 0, "terrain": "swamp", "cougar": True, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 0.5, "terrain": "forest", "cougar": True, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 0, "terrain": "forest", "cougar": True, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 0.5, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 0, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 0.5, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 0, "y": 1, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 1.5, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 1, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 1.5, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 1, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 1.5, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 0, "y": 2, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 2.5, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 2, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 2.5, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 2, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 2.5, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}}]

E3 = [{"x": 0, "y": 0, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 0.5, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 0, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 0.5, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 0, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 0.5, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 0, "y": 1, "terrain": "swamp", "cougar": True, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 1.5, "terrain": "swamp", "cougar": True, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 1, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 1.5, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 1, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 1.5, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 0, "y": 2, "terrain": "mountain", "cougar": True, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 2.5, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 2, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 2.5, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 2, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 2.5, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}}]
      
E4 = [{"x": 0, "y": 0, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 0.5, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 0, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 0.5, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 0, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 0.5, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 0, "y": 1, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 1.5, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 1, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 1.5, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 1, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 1.5, "terrain": "water", "cougar": True, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 0, "y": 2, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 2.5, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 2, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 2.5, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 2, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 2.5, "terrain": "forest", "cougar": True, "bear": False, "structure": {"present": False, "colour": None, "type": None}}]
      
E5 = [{"x": 0, "y": 0, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 0.5, "terrain": "wamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 0, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 0.5, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 0, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 0.5, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 0, "y": 1, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 1.5, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 1, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 1.5, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 1, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 1.5, "terrain": "mountain", "cougar": False, "bear": True, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 0, "y": 2, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 2.5, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 2, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 2.5, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 2, "terrain": "water", "cougar": False, "bear": True, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 2.5, "terrain": "water", "cougar": False, "bear": True, "structure": {"present": False, "colour": None, "type": None}}]

E6 = [{"x": 0, "y": 0, "terrain": "desert", "cougar": False, "bear": True, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 0.5, "terrain": "desert", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 0, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 0.5, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 0, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 0.5, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 0, "y": 1, "terrain": "mountain", "cougar": False, "bear": True, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 1.5, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 1, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 1.5, "terrain": "swamp", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 1, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 1.5, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 0, "y": 2, "terrain": "mountain", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 1, "y": 2.5, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 2, "y": 2, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 3, "y": 2.5, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 4, "y": 2, "terrain": "water", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}},
      {"x": 5, "y": 2.5, "terrain": "forest", "cougar": False, "bear": False, "structure": {"present": False, "colour": None, "type": None}}]